version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building application...
      - aws --version
      - ls -l
      # - chmod +x pipeline/deploy.sh
      # - pipeline/deploy.sh
      

